# Generated by Django 5.0.4 on 2024-05-11 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_uploadedswara_delete_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedSwara',
        ),
    ]
