# Generated by Django 5.0.4 on 2024-05-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raga_app', '0002_rename_audiofile_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
