# Generated by Django 5.0.4 on 2024-05-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raga_app', '0003_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
