# Generated by Django 5.0.4 on 2024-05-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raga_app', '0004_delete_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='audio',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
