# Generated by Django 5.0.4 on 2024-05-10 14:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raga_app', '0005_remove_audio_uploaded_by_alter_audio_uploaded_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio1',
            field=models.FileField(default=datetime.datetime.now, upload_to='swara/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='title1',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='audio',
            name='uploaded_date1',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
