# Generated by Django 5.0.4 on 2024-06-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raga_app', '0006_audio_audio1_audio_title1_audio_uploaded_date1'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='selected_option',
            field=models.CharField(choices=[('song', 'Song'), ('swara', 'Swara')], default='song', max_length=20),
        ),
    ]
